language: minimal
os: linux
dist: jammy

env:
  global:
    - CI=true

before_install:
  - echo "Preparing build environment..."

install:
  - echo "No dependencies to install"

script:
  - echo "hello yash"


cache:
  directories:
    - $HOME/.cache

notifications:
  email: false
