name: Echo Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Print Echo Message
      run: echo "Hello, this is GitHub Actions running successfully!"
