name: Password Rotation

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rotate-password:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run password rotation
      run: |
        chmod +x ./rotate-password.sh
        ./rotate-password.sh
